### PR TITLE
NXmpes arpes import

### PR DESCRIPTION
**Pull request by rettigl**
Required changes to make the nexus loader for pyarpes work with NXmpes_arpes subdefinition files and to allow conversion into momentum space

### CODE REVIEW

**Comment by domna** [comment]
Do you have an example file you can provide for testing this? If possible we could also add a test for loading the file here.

**Comment by rettigl** [comment]
> Do you have an example file you can provide for testing this? If possible we could also add a test for loading the file here.

There is an example notebook now in https://github.com/FAIRmat-NFDI/pynxtools/tree/dev_nxmpes_arpes/examples/mpes
I still need to upload the corresponding data file somewhere.

**Comment by domna** [comment]
I did some additional checks and simplification and ruff formatted the nexus endstation. This is good to go now form my side @rettigl. Testing and linting will then be fixed in #2.

**Review by rettigl — COMMENTED** [review]
LGTM. Let's add further checks etc. in other PRs.
(I cannot approve as I started this PR)

**Pull request merged**
